# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Gabriel\Proyectos\Peals\Deteccion-Python\src\Views\FormMain\form_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(982, 594)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gb_entrada = QtGui.QGroupBox(self.centralwidget)
        self.gb_entrada.setGeometry(QtCore.QRect(10, 10, 521, 541))
        self.gb_entrada.setObjectName(_fromUtf8("gb_entrada"))
        self.img_entrada = QtGui.QLabel(self.gb_entrada)
        self.img_entrada.setGeometry(QtCore.QRect(10, 20, 501, 399))
        self.img_entrada.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_entrada.setText(_fromUtf8(""))
        self.img_entrada.setObjectName(_fromUtf8("img_entrada"))
        self.btn_iniciar = QtGui.QPushButton(self.gb_entrada)
        self.btn_iniciar.setGeometry(QtCore.QRect(320, 430, 91, 41))
        self.btn_iniciar.setObjectName(_fromUtf8("btn_iniciar"))
        self.btn_reiniciar = QtGui.QPushButton(self.gb_entrada)
        self.btn_reiniciar.setGeometry(QtCore.QRect(420, 430, 91, 41))
        self.btn_reiniciar.setObjectName(_fromUtf8("btn_reiniciar"))
        self.cbtn_esCara = QtGui.QCheckBox(self.gb_entrada)
        self.cbtn_esCara.setGeometry(QtCore.QRect(10, 430, 111, 31))
        self.cbtn_esCara.setObjectName(_fromUtf8("cbtn_esCara"))
        self.value_erode = QtGui.QSpinBox(self.gb_entrada)
        self.value_erode.setGeometry(QtCore.QRect(50, 473, 71, 22))
        self.value_erode.setObjectName(_fromUtf8("value_erode"))
        self.value_dilate = QtGui.QSpinBox(self.gb_entrada)
        self.value_dilate.setGeometry(QtCore.QRect(50, 510, 71, 21))
        self.value_dilate.setObjectName(_fromUtf8("value_dilate"))
        self.lbl_erode = QtGui.QLabel(self.gb_entrada)
        self.lbl_erode.setGeometry(QtCore.QRect(10, 473, 31, 20))
        self.lbl_erode.setObjectName(_fromUtf8("lbl_erode"))
        self.lbl_dilate = QtGui.QLabel(self.gb_entrada)
        self.lbl_dilate.setGeometry(QtCore.QRect(10, 508, 31, 21))
        self.lbl_dilate.setObjectName(_fromUtf8("lbl_dilate"))
        self.gb_salida = QtGui.QGroupBox(self.centralwidget)
        self.gb_salida.setGeometry(QtCore.QRect(540, 10, 431, 431))
        self.gb_salida.setObjectName(_fromUtf8("gb_salida"))
        self.img_preprocesamiento = QtGui.QLabel(self.gb_salida)
        self.img_preprocesamiento.setGeometry(QtCore.QRect(10, 240, 199, 175))
        self.img_preprocesamiento.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_preprocesamiento.setText(_fromUtf8(""))
        self.img_preprocesamiento.setObjectName(_fromUtf8("img_preprocesamiento"))
        self.img_mogColoreado = QtGui.QLabel(self.gb_salida)
        self.img_mogColoreado.setGeometry(QtCore.QRect(220, 240, 199, 175))
        self.img_mogColoreado.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_mogColoreado.setText(_fromUtf8(""))
        self.img_mogColoreado.setObjectName(_fromUtf8("img_mogColoreado"))
        self.img_pintar = QtGui.QLabel(self.gb_salida)
        self.img_pintar.setGeometry(QtCore.QRect(220, 40, 199, 175))
        self.img_pintar.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_pintar.setText(_fromUtf8(""))
        self.img_pintar.setObjectName(_fromUtf8("img_pintar"))
        self.img_resultado = QtGui.QLabel(self.gb_salida)
        self.img_resultado.setGeometry(QtCore.QRect(10, 40, 199, 175))
        self.img_resultado.setFrameShape(QtGui.QFrame.StyledPanel)
        self.img_resultado.setText(_fromUtf8(""))
        self.img_resultado.setObjectName(_fromUtf8("img_resultado"))
        self.lbl_resultado = QtGui.QLabel(self.gb_salida)
        self.lbl_resultado.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.lbl_resultado.setObjectName(_fromUtf8("lbl_resultado"))
        self.lbl_pintar = QtGui.QLabel(self.gb_salida)
        self.lbl_pintar.setGeometry(QtCore.QRect(220, 20, 191, 16))
        self.lbl_pintar.setObjectName(_fromUtf8("lbl_pintar"))
        self.lbl_preprocesamiento = QtGui.QLabel(self.gb_salida)
        self.lbl_preprocesamiento.setGeometry(QtCore.QRect(10, 220, 201, 16))
        self.lbl_preprocesamiento.setObjectName(_fromUtf8("lbl_preprocesamiento"))
        self.lbl_mogColoreado = QtGui.QLabel(self.gb_salida)
        self.lbl_mogColoreado.setGeometry(QtCore.QRect(220, 220, 191, 16))
        self.lbl_mogColoreado.setObjectName(_fromUtf8("lbl_mogColoreado"))
        self.gb_redNeuronal = QtGui.QGroupBox(self.centralwidget)
        self.gb_redNeuronal.setGeometry(QtCore.QRect(540, 450, 431, 101))
        self.gb_redNeuronal.setObjectName(_fromUtf8("gb_redNeuronal"))
        self.txt_etiqueta = QtGui.QLineEdit(self.gb_redNeuronal)
        self.txt_etiqueta.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.txt_etiqueta.setInputMask(_fromUtf8(""))
        self.txt_etiqueta.setObjectName(_fromUtf8("txt_etiqueta"))
        self.txt_resultado = QtGui.QLineEdit(self.gb_redNeuronal)
        self.txt_resultado.setGeometry(QtCore.QRect(190, 60, 231, 31))
        self.txt_resultado.setReadOnly(True)
        self.txt_resultado.setObjectName(_fromUtf8("txt_resultado"))
        self.cbtn_clasificar = QtGui.QCheckBox(self.gb_redNeuronal)
        self.cbtn_clasificar.setGeometry(QtCore.QRect(120, 65, 61, 21))
        self.cbtn_clasificar.setObjectName(_fromUtf8("cbtn_clasificar"))
        self.btn_agregarEtiqueta = QtGui.QPushButton(self.gb_redNeuronal)
        self.btn_agregarEtiqueta.setGeometry(QtCore.QRect(320, 20, 101, 31))
        self.btn_agregarEtiqueta.setObjectName(_fromUtf8("btn_agregarEtiqueta"))
        self.rbtn_test = QtGui.QRadioButton(self.gb_redNeuronal)
        self.rbtn_test.setGeometry(QtCore.QRect(120, 30, 41, 17))
        self.rbtn_test.setObjectName(_fromUtf8("rbtn_test"))
        self.rbtn_train = QtGui.QRadioButton(self.gb_redNeuronal)
        self.rbtn_train.setGeometry(QtCore.QRect(170, 30, 41, 17))
        self.rbtn_train.setObjectName(_fromUtf8("rbtn_train"))
        self.txt_cantidad = QtGui.QLineEdit(self.gb_redNeuronal)
        self.txt_cantidad.setGeometry(QtCore.QRect(222, 19, 91, 31))
        self.txt_cantidad.setObjectName(_fromUtf8("txt_cantidad"))
        self.btn_entrenar = QtGui.QPushButton(self.gb_redNeuronal)
        self.btn_entrenar.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.btn_entrenar.setObjectName(_fromUtf8("btn_entrenar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.gb_entrada.setTitle(_translate("MainWindow", "Entrada", None))
        self.btn_iniciar.setText(_translate("MainWindow", "Iniciar", None))
        self.btn_reiniciar.setText(_translate("MainWindow", "Reiniciar", None))
        self.cbtn_esCara.setText(_translate("MainWindow", "Es cara", None))
        self.lbl_erode.setText(_translate("MainWindow", "Erode", None))
        self.lbl_dilate.setText(_translate("MainWindow", "Dilate", None))
        self.gb_salida.setTitle(_translate("MainWindow", "Salida", None))
        self.lbl_resultado.setText(_translate("MainWindow", "Resultado", None))
        self.lbl_pintar.setText(_translate("MainWindow", "Pintar", None))
        self.lbl_preprocesamiento.setText(_translate("MainWindow", "Preprocesamiento", None))
        self.lbl_mogColoreado.setText(_translate("MainWindow", "MOG Coloreado", None))
        self.gb_redNeuronal.setTitle(_translate("MainWindow", "Red Neuronal", None))
        self.txt_etiqueta.setPlaceholderText(_translate("MainWindow", "Etiqueta", None))
        self.cbtn_clasificar.setText(_translate("MainWindow", "Clasificar", None))
        self.btn_agregarEtiqueta.setText(_translate("MainWindow", "Agregar Etiqueta", None))
        self.rbtn_test.setText(_translate("MainWindow", "test", None))
        self.rbtn_train.setText(_translate("MainWindow", "train", None))
        self.txt_cantidad.setPlaceholderText(_translate("MainWindow", "Cantidad", None))
        self.btn_entrenar.setText(_translate("MainWindow", "Entrenar", None))
